-- Drop all tables
DROP TABLE IF EXISTS author, book, foodstat, note, emotion;

-- Add all tables
CREATE TABLE Author
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    authorName VARCHAR(255) NOT NULL
);

-- Insert statements for Author table
INSERT INTO Author (authorName)
VALUES ('Author Name 1');

-- Create table for books
CREATE TABLE Book
(
    id                 BIGINT PRIMARY KEY AUTO_INCREMENT,
    title              VARCHAR(255) NOT NULL,
    author_id          BIGINT       NOT NULL,
    description        VARCHAR(255) NOT NULL,
    totalChapters      INT          NOT NULL,
    currentChapter     INT          NOT NULL,
    totalPages         INT          NOT NULL,
    currentPage        INT          NOT NULL,
    rating DOUBLE NOT NULL,
    isAlreadyRead      BOOLEAN      NOT NULL,
    startReadingDate   DATETIME     NOT NULL,
    endReadingDate     DATETIME     NOT NULL,
    IsCurrentlyReading BOOLEAN      NOT NULL,
    bookOpinion        VARCHAR(255) NOT NULL,
    specialNotes       VARCHAR(255) NOT NULL,
    FOREIGN KEY (author_id) REFERENCES Author (id)
);

-- Insert statements for Book table
INSERT INTO Book (title,
                  author_id,
                  description,
                  totalChapters,
                  currentChapter,
                  totalPages,
                  currentPage,
                  rating,
                  isAlreadyRead,
                  startReadingDate,
                  endReadingDate,
                  IsCurrentlyReading,
                  bookOpinion,
                  specialNotes)
VALUES ('Book Title 1',
        1,
        'Book description 1',
        10,
        5,
        200,
        150,
        4.5,
        FALSE,
        '2023-01-01 00:00:00',
        '2023-02-28 00:00:00',
        FALSE,
        'Book opinion 1',
        'Special notes 1');

-- Create table for emotion
CREATE TABLE Emotion
(
    id      BIGINT PRIMARY KEY AUTO_INCREMENT,
    emotion VARCHAR(255) NOT NULL
);

-- Insert statements for Emotion table
INSERT INTO Emotion (emotion)
VALUES ('Joy');


-- create table for food stat
CREATE TABLE FOODSTAT
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dailyStatus   VARCHAR(255) NOT NULL,
    dateSubmitted TIMESTAMP    NOT NULL
);

-- create table for note
CREATE TABLE Note
(
    id                   BIGINT PRIMARY KEY AUTO_INCREMENT,
    title                VARCHAR(255) NOT NULL,
    actualNote           VARCHAR(255) NOT NULL,
    emotion_id           BIGINT       NOT NULL,
    dateOfNoteSubmission DATETIME     NOT NULL,
    FOREIGN KEY (emotion_id) REFERENCES Emotion (id)
);

-- Insert statements for Note table
INSERT INTO Note (title,
                  actualNote,
                  emotion_id,
                  dateOfNoteSubmission)
VALUES ('Note Title 1',
        'Actual Note 1',
        1,
        '2023-01-01 12:00:00');
